# Wrangler configuration for Trusted Collaboration Tunnel Worker
# Documentation: https://developers.cloudflare.com/workers/wrangler/configuration/

name = "tct-worker"
main = "trusted-collab-worker.js"
compatibility_date = "2024-10-01"

# Account ID
account_id = "6bb2602000d43f7d74e1732825208354"

# Environment variables (non-sensitive)
# For sensitive values (API_KEYS, RECEIPT_HMAC_KEY), use: wrangler secret put <NAME>
[vars]
TERMS_URL = "https://llmpages.org/ai-policy/"
PRICING_URL = "https://llmpages.org/ai-pricing/"
SITEMAP_PATH = "/llm-sitemap.json"
MANIFEST_PATH = "/llms.txt"

# Secrets (use wrangler CLI to set these, never commit to git):
# wrangler secret put API_KEYS
# wrangler secret put RECEIPT_HMAC_KEY

# Routes for llmpages.org
# Note: Wildcard in middle of path not allowed by Cloudflare API
# Deploy worker first, then configure routes in Cloudflare dashboard
# or use a catch-all pattern
#[[routes]]
#pattern = "llmpages.org/*"
#zone_name = "llmpages.org"

# Development configuration
[env.development]
name = "tct-worker-dev"

[env.development.vars]
# AUTH_MODE = "api_key"
# API_KEYS = "dev-test-key-123"           # Dev only - use secrets in production!
# TERMS_URL = "https://dev.yourdomain.com/ai-policy"
# PRICING_URL = "https://dev.yourdomain.com/ai-pricing"

# Production configuration
[env.production]
name = "tct-worker-prod"

# Use wrangler secrets for production:
# wrangler secret put API_KEYS --env production
# wrangler secret put RECEIPT_HMAC_KEY --env production

# Deployment commands:
# - Development: wrangler deploy --env development
# - Production:  wrangler deploy --env production
# - Live logs:   wrangler tail --env production
